import React, { useState } from 'react';
import { AcademicReport, ReportConfig } from '../types';
import { motion, AnimatePresence } from 'motion/react';
import { BookOpen, FileText, Download, Copy, Check, Sparkles, HelpCircle, Edit, Table, Printer, RefreshCw } from 'lucide-react';

const STATIC_PRESETS: { [key: string]: AcademicReport } = {
  database: {
    id: "db_study_preset",
    topicId: "database",
    title: "Comparative Study of Biological Databases: GenBank, UniProt, and Protein Data Bank (PDB)",
    author: "R. Omarradhika, B.Tech Biotechnology",
    date: "June 2026",
    abstract: "Biological databases are essential tools in modern biotechnology, allowing students and researchers to store, retrieve, and analyze gene and protein information. This comparative study examines the three major classes of biological databases: NCBI GenBank for nucleotide sequences, UniProt for protein sequences and functional annotations, and the Protein Data Bank (PDB) for 3D macromolecular structures. By discussing their unique curation standards, file formats (FASTA, flat files, and mmCIF), and cross-referencing capabilities, we present a clear guide for undergraduates. This report highlights how utilizing these primary databases together allows us to bridge the gap between gene sequences and physical 3D protein structures.",
    introduction: `### 1. Introduction and Basic Context
In modern biotechnology, biological databases are the fundamental repositories used to manage the massive amount of data generated by genetic sequencing. In the early days of molecular biology, sequence records were maintained in lab notebooks and local computer files. The establishment of GenBank under the National Center for Biotechnology Information (NCBI) in 1982 provided a centralized, public repository for DNA and RNA sequences.

As the field expanded, protein-specific databases became necessary to store translated amino acid sequences and functional features. In 2002, Swiss-Prot, PIR, and TrEMBL were merged to form the UniProt Knowledgebase (UniProtKB). This became the world standard for looking up protein names, functional roles, active sites, and metabolic pathways.

To study the physical 3D shape of these proteins, structural repositories were also created. In 1971, the Protein Data Bank (PDB) was established. It collects and stores 3D spatial coordinates of proteins determined through experimental biophysics methods like X-ray Crystallography, NMR Spectroscopy, and Cryo-Electron Microscopy (Cryo-EM).

### 2. Overview of NCBI, UniProt, and PDB
Each of the three key databases has a distinct purpose and level of curation:

* **NCBI GenBank**: This is primarily a nucleotide database. GenBank stores DNA and RNA sequences. Because it allows direct submission from laboratories worldwide, it contains a large amount of raw, redundant sequence data. To help students and researchers find clean sequences, NCBI also hosts the RefSeq database, which provides non-redundant, curated reference sequences.
* **UniProt KB**: This is a direct proteomic database. It is split into two sections: Swiss-Prot, which contains manually reviewed and annotated records, and TrEMBL, which contains unreviewed, computer-annotated sequences. UniProt is extremely useful for checking protein domains, residue modifications, cell location, and biological actions.
* **Protein Data Bank (PDB)**: This is a structural database. It does not store text sequences of raw DNA, but rather the actual X, Y, and Z spatial coordinates of every atom within a biomolecule. Each entry under PDB is verified against chemical standards and geometry principles (such as Ramachandran plot scores) to ensure high structural accuracy.`,
    methodology: `### 3. File Formats and Sequence Representation
Biotechnology students must understand the common formats used to store sequence and structural data:

1. **FASTA Format**: This is the simplest text-based format. It begins with a single-line header marked by a \`>\` symbol, followed by the actual single-letter amino acid or nucleotide sequence in clean rows.
2. **GenBank Flat Format (GBFF)**: A highly structured format that includes metadata like source organisms, active citations, and a detailed FEATURES table mapping exons, introns, and coding regions (CDS).
3. **PDB and mmCIF Formats**: Historically, 3D structures were stored as \`.pdb\` text files where each atom coordinate (X, Y, Z) was listed in columns. Due to size limits of the traditional format (which could not label more than 99,999 atoms), the macromolecular Crystallographic Information File (\`mmCIF\`) is now the modern standard because it accommodates infinitely large biological assemblies.`,
    discussion: `### 4. Database Searching and Interoperability
In typical undergraduate projects, these databases are used in a connected sequence. For example, a student starting with an unknown gene sequence will perform an NCBI BLAST search to identify the gene. They will then consult UniProt to find the protein's function, cellular location, and conserved active sites. Finally, they will look up the PDB ID on the RCSB Protein Data Bank to visualize the 3D folding of the protein and locate binding clefts.

This workflow is made possible because these platforms are highly cross-referenced. A single accession number on UniProt (e.g., P69905 for hemoglobin) is linked directly to its GenBank nucleotide ID and its corresponding PDB structure (e.g., 1A3N).

#### 4.1 Simple Databases and Synchronization Challenges
A common bottleneck in informatics is database synchronization. While uncurated data in GenBank/TrEMBL can be uploaded instantly, manual review in Swiss-Prot requires substantial scientific verification. This results in a time lag where newly discovered sequences remain unreviewed. For first/second-year students, understanding these differences is crucial for selecting the most reliable template for molecular modeling.`,
    references: [
      "Altschul, S. F., Gish, W., Miller, W., Myers, E. W., & Lipman, D. J. (1990). Basic local alignment search tool. Journal of Molecular Biology, 215(3), 403-410.",
      "Berman, H. M., Westbrook, J., Feng, Z., Gilliland, G., Bhat, T. N., Weissig, H., ... & Bourne, P. E. (2000). The Protein Data Bank. Nucleic Acids Research, 28(1), 235-242.",
      "UniProt Consortium. (2021). UniProt: the universal protein knowledgebase in 2021. Nucleic Acids Research, 49(D1), D480-D489.",
      "Sayers, E. W., Cavalcoli, J., Clark, K., Ostell, J., Pruitt, K. D., & Sherry, S. T. (2021). Database resources of the National Center for Biotechnology Information. Nucleic Acids Research, 49(D1), D10-D17."
    ],
    comparisonGrid: {
      header: ["Database", "Primary Data Type", "Standard Format", "Curation System", "Key Use for Students"],
      rows: [
        ["NCBI GenBank", "DNA, RNA, Genomes", "FASTA, GBFF", "User submissions + RefSeq curated", "Searching genes, primers, and transcripts"],
        ["UniProt KB", "Protein descriptions & details", "FASTA, Plain Text", "Swiss-Prot (manual) & TrEMBL (automatic)", "Checking protein function & functional domains"],
        ["Protein Data Bank (PDB)", "3D atomic coordinates", "mmCIF, PDB", "wwPDB automated validation", "Visualizing protein folds and drug-active centers"]
      ]
    }
  },
  drug_discovery: {
    id: "drug_discovery_preset",
    topicId: "drug_discovery",
    title: "Principles of Computer-Aided Drug Design (CADD) and Molecular Docking",
    author: "R. Omarradhika, B.Tech Biotechnology",
    date: "June 2026",
    abstract: "The classical process of developing new medicines is slow, taking over 10 years and costing millions of dollars. Computer-Aided Drug Design (CADD) has emerged as an exciting approach to speed up this discovery timeline. This report discusses the basic principles of CADD, focusing on molecular docking, virtual database screening, and predicting chemical properties. By understanding how small chemical ligands are docked into the active pockets of target proteins and sorted by simple energy scores, students can learn how researchers identify promising drug candidates before performing wet-lab chemistry experiments.",
    introduction: `### 1. Introduction to Computational Drug Design
Traditional pharmacology relied heavily on screening thousands of random chemical compounds against active cell lines. This process was extremely inefficient, leading to high failure rates downstream. The availability of high-resolution 3D structures of key target proteins in the Protein Data Bank (PDB) paved the way for "Rational Drug Design."

In Rational Drug Design, computational chemists use three-dimensional models of disease-receptor proteins to design chemical molecules that fit perfectly into the receptor's active sites, resembling a key fitting into a lock. This targeted approach dramatically reduces the number of compounds that need to be made and tested in a wet lab.`,
    methodology: `### 2. Easy Principles of Molecular Docking
Molecular docking is the primary computational method used to study how a small drug molecule (ligand) binds to a target protein (receptor). Docking involves two simple steps:

1. **Conformational Search**: The docking software rotates different single bonds of the ligand molecule to find its most favorable shape inside the protein's binding pocket.
2. **Scoring Potential**: The software calculates an estimated binding energy (Score) for each position. The score combines basic physical forces like hydrogen bonds, electrostatic interactions, and hydrophobic forces. A lower (more negative) binding energy score indicates a stronger, more stable binding fit.

### 3. Public Chemical Databases and Lipinski's Rule of 5
To find new potential drug candidates, docking simulations are run against huge public libraries of chemicals:
* **PubChem**: A massive free repository of chemical structures and bioactivity data hosted by the NCBI.
* **ZINC Database**: A curated catalog of millions of purchaseable chemical structures available in ready-to-dock 3D formats.

Once high-scoring chemical compounds are found, they are checked against "drug-likeness" filters. The most famous filter taught in biotech classes is **Lipinski's Rule of 5**, which predicts whether a compound can be easily absorbed by the human body when taken orally:
1. Molecular weight under 500 Da.
2. High fat-solubility (LogP coefficient less than 5).
3. Fewer than 5 Hydrogen-bond donors.
4. Fewer than 10 Hydrogen-bond acceptors.

By screening out molecules that violate these rules, or predicting ADMET (Absorption, Distribution, Metabolism, Excretion, and Toxicity) behavior using computer algorithms, scientists can avoid toxic or poorly-soluble chemicals early in the research process.`,
    discussion: `### 4. Current Challenges and Simple Horizons
While Computer-Aided Drug Design is incredibly powerful, it has simple limitations. First, protein receptors are often treated as completely static "rigid" shapes by docking programs, whereas real proteins inside the human cell are highly flexible and frequently move. To capture these shifts, researchers use Molecular Dynamics (MD) simulations, which apply physics equations to simulate molecular vibrations over time, though this requires high computing power.

Second, computerized energy scores are helpful approximations rather than perfect predictions. However, for a B.Tech student, utilizing docking platforms remains a crucial training skill to analyze receptor-ligand fits, screen out inactive compounds, and prepare realistic laboratory inputs.`,
    references: [
      "Lipinski, C. A., Lombardo, F., Dominy, B. W., & Feeney, P. J. (2001). Experimental and computational approaches to estimate solubility and permeability in drug discovery and development settings. Advanced Drug Delivery Reviews, 46(1-3), 3-26.",
      "Morris, G. M., Huey, R., Lindstrom, W., Sanner, M. F., Belew, R. K., Poster, D. S., & Olson, A. J. (2009). AutoDock4 and AutoDockTools4: Automated docking with selective receptor flexibility. Journal of Computational Chemistry, 30(16), 2785-2791.",
      "Kitchen, D. B., Decornez, H., Furr, J. R., & Bajorath, J. (2004). Docking and scoring in virtual screening for drug discovery: methods and applications. Nature Reviews Drug Discovery, 3(11), 935-949."
    ]
  },
  machine_learning: {
    id: "ml_bio_preset",
    topicId: "machine_learning",
    title: "Applications of Machine Learning and AlphaFold in Protein Structure Prediction",
    author: "R. Omarradhika, B.Tech Biotechnology",
    date: "June 2026",
    abstract: "The rapid pace of DNA and protein sequencing has produced more biological data than humans can manually analyze. Machine learning (ML) has become a crucial tool in bioinformatics to find patterns in these big datasets. This introductory report explores how basic machine learning works in computational biology. We discuss how simple probabilistic models align sequences, and showcase how Google's AlphaFold revolutionized biochemistry by predicting highly accurate 3D protein structures directly from 1-dimensional amino acid sequences, saving years of physical laboratory effort.",
    introduction: `### 1. The Machine Learning Paradigm in Biology
In biotechnology, sequence analysis is essentially a pattern recognition task. In early days, researchers searched for identical sequences using simple score matrices. As database sizes increased, machine learning models like Hidden Markov Models (HMMs) were introduced to detect motifs, gene boundaries, and sequence alignments by calculating state transition probabilities.

Modern deep learning uses layered artificial neural networks to automatically identify complex biological patterns. By feeding these models sequences and physical 3D templates compiled in the PDB, neural networks can learn the complex rules of amino acid folding directly, without needing human hand-guided parameter configuration.`,
    methodology: `### 2. AlphaFold and the Protein Folding Challenge
For over 50 years, predicting a protein's 3D structural shape purely from its sequence was considered one of the greatest challenges in biochemistry. Google DeepMind's AlphaFold solved this using a deep learning architecture. The simple steps of this prediction process are:

1. **Multiple Sequence Alignment (MSA)**: AlphaFold searches for similar sequences in other species to identify residues that co-evolve. If two positions mutate together across diverse species, they are likely physically close to each other in the 3D folded shape.
2. **Evoformer Representation**: This processes sequence alignment logs and pairwise spatial layouts simultaneously, predicting how residues coordinate.
3. **Structure Modeling**: A final structural block translates these coordinates into continuous 3D physical coordinates, placing carbon chains directly in physical space.

### 3. ESMFold and Generative Protein Design
Beyond AlphaFold, newer and faster tools have emerged:
* **ESMFold**: Developed by Meta AI, this uses a Protein Language Model trained on evolutionary sequences. It functions similarly to text models but predicts 3D folds in fractions of a second, which is useful for rapid screens.
* **Generative Design (e.g., RFdiffusion)**: Generative models can design completely new chemical proteins from scratch. Students can design custom-tailored synthetic enzymes to bind target markers, opening paths for custom diagnostics.`,
    discussion: `### 4. Simple Interpretations and Black-Box Bottlenecks
While ML models are highly accurate, they present a few challenges. The most notable is the "black-box" problem: the neural network is extremely good at outputting a highly accurate 3D structure, but it does not explain the exact physical folding pathway.

Furthermore, machine learning relies heavily on the quality of experimental data in the PDB. For disordered regions or unusual proteins that coordinate metal ions, standard ML algorithms can struggle. Nonetheless, for undergraduate biotechnology, understanding these computational models is key to predicting structures and exploring custom proteins.`,
    references: [
      "Jumper, J., Evans, R., Pritzel, A., Green, T., Figurnov, M., Ronneberger, O., ... & Hassabis, D. (2021). Highly accurate protein structure prediction with AlphaFold. Nature, 596(7873), 583-589.",
      "Watson, J. L., Juergens, D., Bennett, N. R., Trippe, B. L., Yim, J., Eisenach, H. E., ... & Baker, D. (2023). De novo design of protein structure and function with RFdiffusion. Nature, 620(7975), 1089-1100.",
      "Lin, Z., Akin, H., Rao, R., Hie, B., Zhu, Z., Lu, W., ... & Rives, A. (2023). Evolutionary-scale prediction of atomic-level protein structure with a language model. Science, 379(6637), 1123-1130."
    ]
  }
};

export default function ReportBuilder() {
  const [activeTopic, setActiveTopic] = useState<string>('database');
  const [author, setAuthor] = useState<string>('R. Omarradhika, B.Tech Biotechnology');
  const [title, setTitle] = useState<string>('Comparative Study of Biological Databases');
  const [targetOrganism, setTargetOrganism] = useState<string>('');
  const [specificDatabase, setSpecificDatabase] = useState<string>('');
  const [customFocus, setCustomFocus] = useState<string>('');
  const [isCompiling, setIsCompiling] = useState<boolean>(false);
  const [compileStep, setCompileStep] = useState<number>(0);
  const [activeReport, setActiveReport] = useState<AcademicReport>(STATIC_PRESETS['database']);
  const [activePageTab, setActivePageTab] = useState<'abstract' | 'intro' | 'methods' | 'discussion' | 'references'>('abstract');
  const [copyAck, setCopyAck] = useState<boolean>(false);

  // Editable sections state to let them customize their assignment dynamically
  const [editedText, setEditedText] = useState<string>('');
  const [isEditing, setIsEditing] = useState<boolean>(false);

  const steps = [
    "Searching NCBI databases, UniProt API, and PDB references...",
    "Drafting conceptual and theoretical background metrics...",
    "Running structural and positional bioinformatics comparisons...",
    "Compiling and formatting works cited bibliographic grid..."
  ];

  const handleTopicChange = (topic: string) => {
    setActiveTopic(topic);
    setActiveReport(STATIC_PRESETS[topic]);
    setTitle(STATIC_PRESETS[topic].title);
    setActivePageTab('abstract');
  };

  const handleTriggerCompile = async () => {
    setIsCompiling(true);
    setCompileStep(0);

    // Simulate progress ticks
    const interval = setInterval(() => {
      setCompileStep((prev) => {
        if (prev >= 3) {
          clearInterval(interval);
          return 3;
        }
        return prev + 1;
      });
    }, 1500);

    try {
      const response = await fetch('/api/report/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          topicId: activeTopic,
          title,
          author,
          targetOrganism,
          specificDatabase,
          customFocus
        })
      });

      const data = await response.json();
      
      setActiveReport({
        id: `thesis_${Date.now()}`,
        topicId: activeTopic,
        title: title || STATIC_PRESETS[activeTopic].title,
        author: author || "R. Omarradhika, MSc",
        date: new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' }),
        abstract: data.abstract,
        introduction: data.introduction,
        methodology: data.methodology,
        discussion: data.discussion,
        references: data.references,
        comparisonGrid: data.comparisonGrid
      });
      setActivePageTab('abstract');
    } catch (e) {
      console.error("AI Thesis compile failed:", e);
      // fallback to static preset with custom header values
      setActiveReport({
        ...STATIC_PRESETS[activeTopic],
        title,
        author,
        date: "Compiled June 2026"
      });
    } finally {
      clearInterval(interval);
      setIsCompiling(false);
    }
  };

  const handleCopyFullReport = () => {
    const fullText = `TITLE: ${activeReport.title}
AUTHOR: ${activeReport.author}
DATE: ${activeReport.date}

ABSTRACT:
${activeReport.abstract}

INTRODUCTION:
${activeReport.introduction}

METHODOLOGY & storage conventions:
${activeReport.methodology}

DISCUSSION:
${activeReport.discussion}

REFERENCES / WORKS CITED:
${activeReport.references.map((r, i) => `[${i+1}] ${r}`).join('\n')}
`;
    navigator.clipboard.writeText(fullText);
    setCopyAck(true);
    setTimeout(() => setCopyAck(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  const getCurrentPageText = () => {
    switch (activePageTab) {
      case 'abstract': return activeReport.abstract;
      case 'intro': return activeReport.introduction;
      case 'methods': return activeReport.methodology;
      case 'discussion': return activeReport.discussion;
      default: return "";
    }
  };

  const savePageEdits = () => {
    if (!getCurrentPageText()) return;
    const updated = { ...activeReport };
    if (activePageTab === 'abstract') updated.abstract = editedText;
    else if (activePageTab === 'intro') updated.introduction = editedText;
    else if (activePageTab === 'methods') updated.methodology = editedText;
    else if (activePageTab === 'discussion') updated.discussion = editedText;
    setActiveReport(updated);
    setIsEditing(false);
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-6" id="report-builder-root">
      
      {/* LEFT COLUMN: Configuration settings */}
      <div className="lg:col-span-4 bg-white p-6 rounded-2xl border border-gray-100 shadow-sm flex flex-col gap-6">
        <div>
          <h2 className="text-xl font-bold text-gray-800 flex items-center gap-2">
            📚 Thesis Studio <span className="text-xs bg-violet-50 text-violet-700 px-2.5 py-1 rounded-full font-medium">Task 4</span>
          </h2>
          <p className="text-xs text-gray-500 mt-1">
            Build and export standard publication-grade 5-6 page academic reports with deep bibliography resources.
          </p>
        </div>

        {/* Selected mini project topic */}
        <div className="flex flex-col gap-2">
          <label className="text-xs font-semibold text-gray-400 uppercase tracking-wider">Select Thesis Domain</label>
          <div className="flex flex-col gap-1.5">
            <button
              id="topic-btn-db"
              onClick={() => handleTopicChange('database')}
              className={`w-full py-2.5 px-3 text-left text-xs rounded-xl font-medium border transition-all flex items-center gap-2 ${
                activeTopic === 'database'
                  ? 'bg-violet-600 text-white border-violet-600 shadow-md shadow-violet-100'
                  : 'bg-gray-50 hover:bg-gray-100 text-gray-650 border-gray-200'
              }`}
            >
              <Table size={13} />
              <span>Comparative Database Study</span>
            </button>
            <button
              id="topic-btn-drug"
              onClick={() => handleTopicChange('drug_discovery')}
              className={`w-full py-2.5 px-3 text-left text-xs rounded-xl font-medium border transition-all flex items-center gap-2 ${
                activeTopic === 'drug_discovery'
                  ? 'bg-violet-600 text-white border-violet-600 shadow-md shadow-violet-100'
                  : 'bg-gray-50 hover:bg-gray-100 text-gray-650 border-gray-200'
              }`}
            >
              <BookOpen size={13} />
              <span>Role in Drug Discovery</span>
            </button>
            <button
              id="topic-btn-ml"
              onClick={() => handleTopicChange('machine_learning')}
              className={`w-full py-2.5 px-3 text-left text-xs rounded-xl font-medium border transition-all flex items-center gap-2 ${
                activeTopic === 'machine_learning'
                  ? 'bg-violet-600 text-white border-violet-600 shadow-md shadow-violet-100'
                  : 'bg-gray-50 hover:bg-gray-100 text-gray-650 border-gray-200'
              }`}
            >
              <Sparkles size={13} />
              <span>Machine Learning Applications</span>
            </button>
          </div>
        </div>

        {/* Configurations Fields */}
        <div className="flex flex-col gap-3.5 border-t border-gray-100 pt-4">
          <label className="text-xs font-semibold text-gray-400 uppercase tracking-wider">Thesis Customizers</label>
          
          <div>
            <span className="text-[10px] text-gray-400 block mb-1">Author Name</span>
            <input
              type="text"
              id="report-author-input"
              value={author}
              onChange={(e) => setAuthor(e.target.value)}
              placeholder="e.g. R. Omarradhika"
              className="w-full text-xs p-2 bg-gray-50 border border-gray-200 rounded-lg focus:outline-none"
            />
          </div>

          <div>
            <span className="text-[10px] text-gray-400 block mb-1">Custom Master Title</span>
            <textarea
              rows={2}
              id="report-title-input"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="Thesis Master Title"
              className="w-full text-xs p-2 bg-gray-50 border border-gray-200 rounded-lg focus:outline-none"
            />
          </div>

          <div>
            <span className="text-[10px] text-gray-400 block mb-1">Target Organisms / Environs (Optional)</span>
            <input
              type="text"
              id="report-organism-input"
              value={targetOrganism}
              onChange={(e) => setTargetOrganism(e.target.value)}
              placeholder="e.g. Homo Sapiens / SARS-CoV-2 Spike"
              className="w-full text-xs p-2 bg-gray-50 border border-gray-200 rounded-lg focus:outline-none"
            />
          </div>

          <div>
            <span className="text-[10px] text-gray-400 block mb-1">Focal Database / Computational Tools (Optional)</span>
            <input
              type="text"
              id="report-tool-input"
              value={specificDatabase}
              onChange={(e) => setSpecificDatabase(e.target.value)}
              placeholder="e.g. PDB, Autodock, AlphaFold"
              className="w-full text-xs p-2 bg-gray-50 border border-gray-200 rounded-lg focus:outline-none"
            />
          </div>

          <div>
            <span className="text-[10px] text-gray-400 block mb-1">Custom Scientific Hypotheses (Optional)</span>
            <input
              type="text"
              id="report-focus-input"
              value={customFocus}
              onChange={(e) => setCustomFocus(e.target.value)}
              placeholder="e.g. Impact of single mutations on folding affinity"
              className="w-full text-xs p-2 bg-gray-50 border border-gray-200 rounded-lg focus:outline-none"
            />
          </div>
        </div>

        {/* Compile Thesis trigger */}
        <button
          id="compile-thesis-btn"
          disabled={isCompiling}
          onClick={handleTriggerCompile}
          className="w-full mt-auto bg-violet-600 hover:bg-violet-700 text-white py-3 rounded-2xl text-xs font-bold transition flex items-center justify-center gap-2 shadow-lg shadow-violet-100 disabled:opacity-50"
        >
          {isCompiling ? (
            <>
              <RefreshCw className="animate-spin" size={13} />
              Compiling peer-reviewed manuscript...
            </>
          ) : (
            <>
              <FileText size={14} />
              Compile Custom Academic Report
            </>
          )}
        </button>

        {/* Compilation progress bars */}
        {isCompiling && (
          <div className="p-4 bg-slate-900 text-[10px] text-emerald-400 rounded-xl font-mono flex flex-col gap-2">
            <div className="flex justify-between font-bold border-b border-slate-800 pb-1 text-[10px]">
              <span>BIOTHEM LANGUAGE PARSER RUNNING</span>
              <span className="animate-pulse">● BUILDING</span>
            </div>
            {steps.map((step, sIdx) => (
              <div 
                key={sIdx} 
                className={`flex gap-2 transition-opacity duration-300 ${sIdx > compileStep ? 'opacity-30' : 'opacity-100'}`}
              >
                <span>{sIdx < compileStep ? '✓' : (sIdx === compileStep ? '▶' : '○')}</span>
                <span>{step}</span>
              </div>
            ))}
          </div>
        )}

      </div>

      {/* RIGHT COLUMN: Professional Paginated Document Layout Preview */}
      <div className="lg:col-span-8 flex flex-col gap-6">
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm flex flex-col overflow-hidden relative" id="printable-area">
          
          {/* Header Controls */}
          <div className="p-4 bg-slate-50 border-b border-gray-100 flex flex-col md:flex-row justify-between items-start md:items-center gap-3 select-none print:hidden">
            <div className="flex flex-wrap gap-1">
              {(['abstract', 'intro', 'methods', 'discussion', 'references'] as const).map((tab) => (
                <button
                  key={tab}
                  id={`tab-btn-${tab}`}
                  onClick={() => {
                    setActivePageTab(tab);
                    setIsEditing(false);
                  }}
                  className={`py-1.5 px-3 rounded-xl text-xs font-bold transition ${activePageTab === tab ? 'bg-violet-600 text-white shadow-sm' : 'hover:bg-gray-150 text-gray-550'}`}
                >
                  {tab.toUpperCase()}
                </button>
              ))}
            </div>

            <div className="flex gap-2">
              <button
                id="btn-edit-page"
                onClick={() => {
                  if (activePageTab !== 'references') {
                    setEditedText(getCurrentPageText());
                    setIsEditing(!isEditing);
                  }
                }}
                disabled={activePageTab === 'references'}
                className="flex items-center gap-1.5 border border-gray-250 py-1 px-2.5 rounded-xl text-xs text-gray-600 hover:bg-gray-50 font-semibold transition disabled:opacity-30"
              >
                <Edit size={12} />
                Edit Page
              </button>
              <button
                id="btn-copy-report"
                onClick={handleCopyFullReport}
                className="flex items-center gap-1.5 bg-slate-900 border border-slate-950 py-1 px-2.5 rounded-xl text-xs text-white hover:bg-slate-800 font-semibold transition"
              >
                {copyAck ? <Check size={12} className="text-emerald-400" /> : <Copy size={12} />}
                {copyAck ? 'Copied Manuscript' : 'Copy All'}
              </button>
              <button
                id="btn-print-report"
                onClick={handlePrint}
                className="flex items-center gap-1 border border-gray-250 py-1 px-2 text-xs text-gray-500 hover:text-gray-700 transition"
                title="Print alignment layout (PDF)"
              >
                <Printer size={12} />
              </button>
            </div>
          </div>

          {/* Actual Academic Paper Sheet Layout */}
          <div className="p-10 md:p-14 text-slate-850 font-serif leading-relaxed text-sm select-text flex flex-col min-h-[550px] shadow-sm flex-1">
            
            {/* Title Block on first page views */}
            {activePageTab === 'abstract' && (
              <div className="text-center border-b border-gray-200 pb-10 mb-10">
                <p className="text-[10px] uppercase font-mono tracking-widest text-indigo-500 font-bold mb-3 select-none">
                  BIOMEDICAL & COMP BIO ACADEMIC PORTFOLIO
                </p>
                <h1 className="text-2xl font-bold leading-tight text-slate-900 max-w-[550px] mx-auto font-serif">
                  {activeReport.title}
                </h1>
                <div className="mt-5 flex flex-col gap-1 items-center">
                  <p className="font-medium text-xs text-slate-700">{activeReport.author}</p>
                  <p className="text-[10px] text-gray-400 font-mono">{activeReport.date} | Department of Bioinformatics Hub</p>
                </div>
              </div>
            )}

            {/* In-page editing window */}
            {isEditing ? (
              <div className="flex flex-col gap-3 h-full flex-1">
                <div className="text-xs font-bold text-gray-400 uppercase tracking-widest">Editing mode - {activePageTab}</div>
                <textarea
                  rows={15}
                  value={editedText}
                  onChange={(e) => setEditedText(e.target.value)}
                  className="w-full p-4 border border-indigo-400 font-sans text-xs focus:ring-0 focus:outline-none rounded-xl bg-gray-50/50"
                />
                <div className="flex gap-2 justify-end">
                  <button
                    id="save-edit-btn"
                    onClick={savePageEdits}
                    className="bg-emerald-600 hover:bg-emerald-700 text-white font-semibold py-1.5 px-4 rounded-xl text-xs transition"
                  >
                    Save Changes
                  </button>
                  <button
                    id="cancel-edit-btn"
                    onClick={() => setIsEditing(false)}
                    className="text-gray-500 hover:underline py-1.5 px-3 text-xs"
                  >
                    Cancel
                  </button>
                </div>
              </div>
            ) : (
              <div className="flex-1 flex flex-col justify-between">
                
                {/* Abstracts Special Rendering */}
                {activePageTab === 'abstract' && (
                  <div className="flex flex-col gap-6">
                    <div className="bg-slate-50 border-l-4 border-violet-600 p-6 rounded-xl italic">
                      <b className="not-italic text-xs font-bold uppercase tracking-wider text-violet-700 block mb-2 font-mono">Abstract</b>
                      <p className="text-xs leading-relaxed text-slate-650 font-sans">{activeReport.abstract}</p>
                    </div>

                    {/* Integrated Database Comparison Grid (Task 4 core study asset) */}
                    {activeReport.topicId === 'database' && activeReport.comparisonGrid && (
                      <div className="mt-4 flex flex-col gap-3">
                        <h4 className="text-xs font-black text-slate-750 uppercase font-sans tracking-wider border-b pb-1">
                          Table 1.1: Multi-lateral Database Structural Comparison Matrix
                        </h4>
                        <div className="overflow-x-auto border border-gray-150 rounded-xl">
                          <table className="min-w-full text-[10px] font-sans">
                            <thead className="bg-slate-100 text-slate-800 border-b border-gray-200">
                              <tr>
                                {activeReport.comparisonGrid.header.map((head, hi) => (
                                  <th key={hi} className="py-2.5 px-3 text-left font-bold">{head}</th>
                                ))}
                              </tr>
                            </thead>
                            <tbody className="divide-y divide-gray-150 bg-white">
                              {activeReport.comparisonGrid.rows.map((row, ri) => (
                                <tr key={ri} className="hover:bg-slate-50 transition">
                                  {row.map((cell, ci) => (
                                    <td key={ci} className="py-2.5 px-3 font-medium text-slate-650 max-w-[150px] truncate" title={cell}>{cell}</td>
                                  ))}
                                </tr>
                              ))}
                            </tbody>
                          </table>
                        </div>
                      </div>
                    )}
                  </div>
                )}

                {/* Subsections contents parser */}
                {activePageTab !== 'abstract' && activePageTab !== 'references' && (
                  <div className="prose prose-sm max-w-none text-slate-800 leading-relaxed font-serif text-sm">
                    {getCurrentPageText().split('\n').map((line, curIdx) => {
                      if (line.startsWith('###')) {
                        return <h4 key={curIdx} className="text-base font-bold text-slate-900 mt-6 mb-3 font-serif border-b border-gray-100 pb-1">{line.replace('###', '').trim()}</h4>;
                      } else if (line.startsWith('##')) {
                        return <h3 key={curIdx} className="text-lg font-bold text-slate-900 mt-8 mb-4 font-serif">{line.replace('##', '').trim()}</h3>;
                      } else if (line.startsWith('*') || line.startsWith('-')) {
                        return <li key={curIdx} className="ml-5 list-disc mb-1.5">{line.substring(2)}</li>;
                      }
                      return <p key={curIdx} className="mb-4 indent-8 text-justify">{line}</p>;
                    })}
                  </div>
                )}

                {/* Bibliography details */}
                {activePageTab === 'references' && (
                  <div className="flex flex-col gap-6">
                    <h3 className="text-lg font-bold text-slate-900 border-b border-gray-200 pb-2 mb-4 font-serif">
                      Academic Works Cited / Bibliography
                    </h3>
                    <div className="flex flex-col gap-4 font-sans text-xs">
                      {activeReport.references.map((ref, rInd) => (
                        <div key={rInd} className="pl-6 -indent-6 leading-relaxed text-slate-650">
                          <span className="font-bold font-mono mr-2">[{rInd + 1}]</span>
                          {ref}
                        </div>
                      ))}
                    </div>
                  </div>
                )}
                
              </div>
            )}
            
            {/* Standard Pagination Footer line */}
            <div className="border-t border-gray-100 pt-5 mt-10 flex justify-between items-center text-[10px] text-gray-400 font-mono select-none print:hidden">
              <span>OmniBio Academic Publisher Hub</span>
              <span className="capitalize">{activePageTab} Page</span>
            </div>

          </div>

        </div>
      </div>

    </div>
  );
}
